name: Deploy GISIT Backend
on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --ignore-platform-req=ext-rdkafka

      - name: cp .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run Laravel tests
        run: php artisan test

  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /var/www
            make pull-backend
